### ISSUE TITLE
请问：本地运行，基金列表的数据 需要 另外加载吗？

### ISSUE THREAD

**Issue by karlzheng** [axiaoxin-com/investool#51]
**Describe the bug**
本地运行基金列表的数据没有显示

**Screenshots**
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/2570701/203674176-f4d011dd-ba93-4b8a-94df-a345d5fa77da.png">

**Desktop (please complete the following information):**
 - OS:  OSX 12
 - Browser : chrome, safari

**Comment by axiaoxin** [comment]
#46

**Comment by axiaoxin** [comment]
#47
